# Use postgres/example user/password credentials
version: '3.1'

services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/restra -user=restra -password=restra -connectRetries=60 migrate
    volumes:
      - ${PWD}/src/main/resources/migrations:/flyway/sql
  db:
    image: postgres:15.0
    restart: always
    environment:
      - POSTGRES_USER=restra # database with same name created automatically
      - POSTGRES_PASSWORD=restra #password MUST be set, cannot be blank
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "restra" ]
      interval: 5s
      timeout: 1s
      retries: 2
